version: '3'

services:
  acr-backend:
    container_name: backend_container
    restart: always
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - acr-database
    volumes:
      - ./backend:/app

  acr-database:
    container_name: database_container
    restart: always
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: sporting_database_connection_GUGf983YDR34535Dtdt
      MYSQL_DATABASE: academiasporting
      MYSQL_PASSWORD: sporting_database_connection_GUGf983YDR34535Dtdt
    image: mysql:latest
    ports:
      - "3306:3306"
      - "33060:33060"

volumes:
  mysql-data:

networks:
  default:
    external:
      name: acr-network