version: '3'

services:
  acr-backend:
    container_name: backend_container
    restart: always
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - acr-database
    volumes:
      - backend-volume:/app/images 
    env_file:
      - backend.env

  acr-database:
    container_name: database_container
    restart: always
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    env_file:
      - db.env
    image: mysql:latest
    ports:
      - "3306:3306"
      - "33060:33060"

volumes:
  mysql-data:
  backend-volume:

networks:
  default:
    external:
      name: acr-network